device_tree.tcl: Update cpu references for pmu node
zynqmp.dtsi has cpu references in pmu node which default has 4 cpus
mentioned which causing issue if design has less cpus as DTG removes
other nodes.

Update interrupt-affinity property from pmu node as per the design.

ERROR: /pmu: Reference to non-existent node or label "cpu2/cpu3"

Signed-off-by: Raju Kumar Pothuraju <rajukumar.pothuraju@amd.com>
Acked-by: Varalaxmi Bingi <Varalaxmi.bingi@amd.com>